### ISSUE TITLE
프로젝트 페이지에 걸린 링크인 http://aheui.github.io/jsaheui 로 접속할 수 없습니다

### ISSUE THREAD

**Issue by youknowone** [aheui/jsaheui#1]

**Comment by rdebath** [comment]
That's weird, I guess it's got something to do with the aheui.github.io repo in  "aheui".
The interpreter is runnable from this URL though 
https://rawgit.com/aheui/jsaheui/gh-pages/index.html

**Comment by dittos** [comment]
Fixed by 60e6d14.
